name: Publish Package

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
      fail-fast: false

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pipx
        run: python -m pip install --user pipx

      - name: Install Poetry
        run: |
          python -m pipx ensurepath
          pipx install poetry
          poetry config virtualenvs.create false

      - name: Build and Publish Package
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          poetry build
          poetry publish --username $PYPI_USERNAME --password $PYPI_PASSWORD