name: Test

on:
  push:
    branches:
      - main 
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pipx
        run: python -m pip install --user pipx
      - name: Install Poetry
        run: |
          python -m pipx ensurepath
          pipx install poetry
      - name: Install dependencies
        run: poetry install
    #   - name: Lint
    #     run: bash scripts/lint.sh
    #   - run: mkdir coverage
      - name: Test
        # run: bash scripts/test.sh
        run: poetry run pytest
        # env:
        #   COVERAGE_FILE: coverage/.coverage.${{ runner.os }}-py${{ matrix.python-version }}
        #   CONTEXT: ${{ runner.os }}-py${{ matrix.python-version }}